[CAP-400] - implement assign task component
jobfaironline/jobfair-frontend pull request #177
Opened 2022-05-15 13:30 UTC by CaoSon1909

2022-06-05 16:12 UTC, ZERO-94 requested changes

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +  const getTableColumns = async (dayRange) => {
column file ?

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +  const getDataSource = async (staffAssignments, staffs, dayRange, shiftData) => {
separate file ?

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +  const getStaffList = async (assignments) => {
separate file

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +  const getStaffAssignments = async (assignments, shiftData) => {
separate file

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +            const result = {
mapper

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +    for (let i = 0; i < tableData.oldDataSource.length; i++) {
separate file ?

2022-06-05 16:12 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +  const onFilterData = (values) => {
separate file ?

2022-06-06 08:15 UTC, ZERO-94 commented on jobfair-frontend/src/components/forms/ScheduleJobFairForm/ScheduleJobFairForm.component.jsx
> +  return {
mapper ???

2022-06-06 08:17 UTC, ZERO-94 commented on jobfair-frontend/src/containers/AssignTask/column/AssignTask.column.js
> +export const getTableColumns = async (dayRange, handleOpenAssignTaskModal) => {
async ?

2022-06-06 12:03 UTC, TienTruong2000 commented on jobfair-frontend/src/containers/AssignTask/AssignTask.container.jsx
> +    beginTime: tableData.dayRange[selectedCellData.date].beginTime.valueOf() + shiftData[shiftIndex].beginTime,
this is a mapper

2022-06-06 12:07 UTC, TienTruong2000 commented on jobfair-frontend/src/components/forms/ScheduleJobFairForm/ScheduleJobFairForm.component.jsx
> +  return {
this is a mapper

2022-06-07 03:01 UTC, ZERO-94 commented on jobfair-frontend/src/containers/OrganizeJobFair/OrganizeJobFair.container.jsx
>        const body = {
@TienTruong2000 
here

2022-06-07 04:46 UTC, ZERO-94 approved these changes

2022-06-07 04:47 UTC, merged